# -*- coding: utf-8 -*-
"""bilgisayar proje

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oAboUQQMrHaE0mWrTIUH3nXYezNtiIu4
"""

print("Çevrimiçi analiz hesaplayıcıya hoşgeldiniz. Ne yapmak istersiniz?")
Birim_dönüsümü="1"
Analiz_hesaplama="2"
Grafik_çizimi="3"
a=input("Yapmak istediğiniz analizin numarasını yazınız(Birim dönüşümü=1, Analiz hesaplama=2, Grafik çizimi=3):")
if a=="1":
 mg_L="1"
 g_L="2"
 mg_mL="3"
 g_mL="4"
 mg_cm_3="5"
 kg_m_3="6"
 y=input("Biriminizin numarasını giriniz(mg/L=1, g/L=2, mg/mL=3, g/mL=4, mg/cm3=5, kg/m3=6):")
 z=input("Dönüştürülecek birimin numarasını giriniz(mg/L=1, g/L=2, mg/mL=3, g/mL=4, mg/cm3=5, kg/m3=6):")
 if y=="1" and z=="2":
  t=float(input("Miktarı giriniz:"))
  sonuç=t*1000
  print(t,"mg/L=",sonuç,"g/L")
 elif y=="1" and z=="3":
  t=float(input("Miktarı giriniz:"))
  sonuç=t/1000
  print(t,"mg/L=",sonuç,"mg/mL")
 elif y=="1" and z=="4":
  t=float(input("miktarı giriniz:"))
  sonuç=t/1000000
  print(t,"mg/L=",sonuç,"g/mL")
 elif y=="1" and z=="5":
  t=float(input("miktarı giriniz:"))
  sonuç=t/1000
  print(t,"mg/L=",sonuç,"kg/m3")
 elif y=="1" and z=="6":
  t=float(input("miktarı giriniz:"))
  sonuç=t/1000
  print(t,"mg/L=",sonuç,"kg/m3")
 elif y=="2" and z=="1":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1000
  print(t,"g/L=",sonuç,"mg/L")
 elif y=="2" and z=="3":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1
  print(t,"g/L=",sonuç,"mg/mL")
 elif y=="2" and z=="4":
  t=float(input("miktarı giriniz:"))
  sonuç=t/1000
  print(t,"g/L=",sonuç,"g/mL")
 elif y=="2" and z=="5":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1
  print(t,"g/L=",sonuç,"mg/cm3")
 elif y=="2" and z=="6":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1
  print(t,"g/L=",sonuç,"kg/m3")
 elif y=="3" and z=="1":
  t=float(input("miktarı giriniz:"))
  sonuç=t/1000
  print(t,"mg/mL=",sonuç,"mg/L")
 elif y=="3" and z=="2":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1
  print(t,"mg/mL=",sonuç,"g/L")
 elif y=="3" and z=="4":
  t=float(input("miktarı giriniz:"))
  sonuç=t/1000
  print(t,"mg/mL=",sonuç,"g/mL")
 elif y=="3" and z=="5":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1
  print(t,"mg/mL=",sonuç,"mg/cm3")
 elif y=="3" and z=="6":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1
  print(t,"mg/mL=",sonuç,"kg/m3")
 elif y=="4" and z=="1":
  t=float(input("miktarı giriniz:"))
  sonuç=t/1000000
  print(t,"g/mL=",sonuç,"mg/L")
 elif y=="4" and z=="2":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1000
  print(t,"g/mL=",sonuç,"g/L")
 elif y=="4" and z=="3":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1000
  print(t,"g/mL=",sonuç,"mg/mL")
 elif y=="4" and z=="5":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1000
  print(t,"g/mL=",sonuç,"mg/cm3")
 elif y=="4" and z=="6":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1000
  print(t,"g/mL=",sonuç,"kg/m3")
 elif y=="5" and z=="1":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1000
  print(t,"mg/cm3=",sonuç,"mg/L")
 elif y=="5" and z=="2":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1
  print(t,"mg/cm3=",sonuç,"g/L")
 elif y=="5" and z=="3":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1
  print(t,"mg/cm3=",sonuç,"mg/mL")
 elif y=="5" and z=="4":
  t=float(input("miktarı giriniz:"))
  sonuç=t/1000
  print(t,"mg/cm3=",sonuç,"g/mL")
 elif y=="5" and z=="6":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1
  print(t,"mg/cm3=",sonuç,"kg/m3")
 elif y=="6" and z=="1":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1000
  print(t,"kg/m3=",sonuç,"mg/L")
 elif y=="6" and z=="2":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1
  print(t,"kg/m3=",sonuç,"g/L")
 elif y=="6" and z=="3":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1
  print(t,"kg/m3=",sonuç,"mg/mL")
 elif y=="6" and z=="4":
  t=float(input("miktarı giriniz:"))
  sonuç=t/1000
  print(t,"kg/m3=",sonuç,"g/mL")
 elif y=="6" and z=="5":
  t=float(input("miktarı giriniz:"))
  sonuç=t*1
  print(t,"kg/m3=",sonuç,"mg/cm3")
 else:
  print("Hata,lütfen seçimlerinizi kontrol edip tekrar deneyiniz.")
elif a=="2":
 KOİ="1"
 BOİ="2"
 Asidite="3"
 Alkalinite="4"
 Toplam_Sertlik="5"
 Sülfat="6"
 Amonyak="7"
 Klor="8"
 Fosfor="9"
 b=input("Hangi parametreyi hesaplamak istiyorsanız  giriniz.(KOİ=1, BOİ=2, Asidite=3, Alkalinite=4, Toplam sertlik=5, Sülfat=6, Amonyak=7, Klor=8, Fosfor=9):")
 if b==KOİ:
  A=float(input("Şahit numune için kullanılan demir amonyum sülfat çözeltisi miktarı (mL)="))
  B=float(input("Numune için kullanılan demir amonyum sülfat çözeltisi miktarı (mL)="))
  N=float(input("Demir amonyum sülfat çözeltisinin normalitesi="))
  Q=float(input("Numunenin hacmi(mL)="))
  KOİ_degeri=(A-B)*N*8000/Q
  print("KİMYASAL OKSİJEN İHTİYACI=",KOİ_degeri)
 elif b==BOİ:
  x=input("BOİ hesaplamasında seyreltme suyunu aşılı mı kullandınız?")
  if x=="evet":
   D1=float(input("Seyreltilmiş numunenin hazırlandıktan hemen sonraki ÇO konsantrasyonu (mg/L)="))
   D2=float(input("Seyreltilmiş numunenin 5 günlük inkübasyondan sonraki ÇO konsantrasyonu (mg/L)="))
   B1=float(input("Aşılı kontrol numunesinin başlangıçtaki ÇO konsantrasyonu (mg/L)="))
   B2=float(input("Aşılı kontrol numunesinin 5 günlük inkübasyondan sonraki ÇO konsantrasyonu (mg/L)="))
   P=float(input("Kullanılan numunenin desimal hacim kesri"))
   f=float(input("Numunedeki aşının, kontrol numunesindeki aşıya oranı(D1'deki aşı yüzdesi/B1'deki aşı yüzdesi):"))
   BOİ_degeri=(D1-D2)-(B1-B2)*f/P
   print(BOİ_degeri)
  elif x=="hayır":
   D1=float(input("Seyreltilmiş numunenin hazırlandıktan hemen sonraki ÇO konsantrasyonu (mg/L)="))
   D2=float(input("Seyreltilmiş numunenin 5 günlük inkübasyondan sonraki ÇO konsantrasyonu (mg/L)="))
   P=float(input("Kullanılan numunenin desimal hacim kesri"))
   BOİ_degeri=(D1-D2)/P
   print(BOİ_degeri)
  else:
   print("Lütfen işlem yapılabilmesi için evet veya hayır kullanınız.")
 elif b==Asidite:
  s=input("Hesaplamak istediğiniz asidite türü nedir?")
  if s=="toplam asidite":
   A=float(input("Sarfiyat (toplam)="))
   N=float(input("Sarfiyatı yapılan bazın normalitesi="))
   L=float(input("Numune hacmi(ml)="))
   Toplam_Asidite_mg_L_CaCO3 = A*N*50000/L
   print("Toplam asidite=",Toplam_Asidite_mg_L_CaCO3,"mg CaCO3/L")
  elif s=="mineral asidite":
   B=float(input("Sarfiyat (metil oranj dönüm noktasına kadar yapılan sarfiyat)="))
   N=float(input("Sarfiyatı yapılan bazın normalitesi="))
   L=float(input("Numune hacmi(ml)="))
   Mineral_Asidite_mg_L_CaCO3 = B*N*50000/L
   print("Mineral asiditesi=",Mineral_Asidite_mg_L_CaCO3,"mg CaCO3/L")
  elif s=="karbondioksit asiditesi":
   A=float(input("Sarfiyat (toplam asidite için)="))
   N=float(input("Sarfiyatı yapılan bazın normalitesi(toplam asidite için)="))
   L=float(input("Numune hacmi(ml)(toplam asidite için)="))
   Toplam_Asidite_mg_L_CaCO3 = A*N*50000/L
   B=float(input("Sarfiyat (metil oranj dönüm noktasına kadar yapılan sarfiyat)(mineral asidite için)="))
   N=float(input("Sarfiyatı yapılan bazın normalitesi(mineral asidite için)="))
   L=float(input("Numune hacmi(ml)(mineral asidite için)="))
   Mineral_Asidite_mg_L_CaCO3 = B*N*50000/L
   Karbondioksit_Asidite_mg_L_CaCO3=Toplam_Asidite_mg_L_CaCO3-Mineral_Asidite_mg_L_CaCO3
   print("Karbondioksit asiditesi=",Karbondioksit_Asidite_mg_L_CaCO3,"mg CaCO3/L")
  else:
   print("Hesaplanacak asiditenin adını mineral asidite,karbondioksit asiditesi veya toplam asidite şeklinde giriniz.")
 elif b==Alkalinite:
  s=input("Hesaplamak istediğiniz alkalinite türü nedir?")
  if s=="toplam alkalinite":
   A=float(input("Sarfiyat (toplam)="))
   N=float(input("Sarfiyatı yapılan asidin normalitesi="))
   L=float(input("Numune hacmi(ml)="))
   Toplam_Alkalinite_mg_L_CaCO3 = A*N*50000/L
   print("Toplam Alkalinite=",Toplam_Alkalinite_mg_L_CaCO3,"mg CaCO3/L")
  elif s=="fenolftalein alkalinitesi":
   B=float(input("Sarfiyat (fenolftalein dönüm noktasına kadar yapılan sarfiyat)="))
   N=float(input("Sarfiyatı yapılan asidin normalitesi="))
   L=float(input("Numune hacmi(ml)="))
   Fenolftalein_Alkalinite_mg_L_CaCO3 = B*N*50000/L
   print("Fenolftalein Alkalinitesi=",Fenolftalein_Alkalinite_mg_L_CaCO3,"mg CaCO3/L")
  elif s=="metil oranj alkalinitesi":
   A=float(input("Sarfiyat (toplam)="))
   N=float(input("Sarfiyatı yapılan asidin normalitesi(toplam alkalinite için)="))
   L=float(input("Numune hacmi(ml)(toplam alkalinite için)="))
   Toplam_Alkalinite_mg_L_CaCO3 = A*N*50000/L
   B=float(input("Sarfiyat (fenolftalein dönüm noktasına kadar yapılan sarfiyat)(fenolftalein alkalinitesi için)="))
   N=float(input("Sarfiyatı yapılan asidin normalitesi(fenolftalein alkalinitesi için)="))
   L=float(input("Numune hacmi(ml)(fenolftalein alkalinitesi için)="))
   Fenolftalein_Alkalinite_mg_L_CaCO3 = B*N*50000/L
   Metil_oranj_alkalinitesi=Toplam_Alkalinite_mg_L_CaCO3-Fenolftalein_Alkalinite_mg_L_CaCO3
   print("Metil Oranj Asiditesi=",Metil_oranj_alkalinitesi,"mg CaCO3/L")
  else:
   print("Hesaplanacak alkalinitenin adını metil oranj alkalinitesi,fenolftalein alkalinitesi,toplam alkalinite şeklinde giriniz.")
 elif b==Toplam_Sertlik:
  R=float(input("EDTA sarfiyatını giriniz(mL)="))
  P=float(input("1 mL EDTA çözeltisinin CaCO3 cinsinden eşdeğeri="))
  v=float(input("Numunenin hacmi(mL)="))
  Toplam_Sertlik=R*P*1000/v
  print("Toplam Sertlik=",Toplam_Sertlik,"mg CaCO3/L")
 elif b==Sülfat:
  ı=float(input("Gravimetrik sülfat tayini için baryum sülfatın mg değerini giriniz="))
  y=float(input("Gravimetrik sülfat tayini için mL cinsinden numunenin miktarını giriniz="))
  Sülfat_mg_L=ı*0.4115/y
  print("Sülfat=",Sülfat_mg_L,"mg SO4/L")
 elif b==Amonyak:
  o=input("Hangi numunenin amonyak tayinini yapmak istiyorsunuz?(su numunesi,çamur ve sediment numunesi)")
  if o=="su numunesi":
   j=float(input("Numunenin titrasyonu için sarf edilen mL H2SO4 miktarı="))
   h=float(input("Şahidin titrasyonu için sarf edilen mL H2SO4 miktarı="))
   l=float(input("Numunenin hacmi (mL)="))
   mg_Amonyak_L=(j-h)*280/l
   print("Amonyak=",mg_Amonyak_L,"mg NH3/L")
  elif o=="çamur ve sediment numunesi":
   j=float(input("Numunenin titrasyonu için sarf edilen mL H2SO4 miktarı="))
   h=float(input("Şahidin titrasyonu için sarf edilen mL H2SO4 miktarı="))
   ü=float(input("g kuru numune ağırlığı="))
   mg_Amonyak_kg=(j-h)*280/ü
   print("Amonyak=",mg_Amonyak_kg,"mg NH3/kg")
  else:
   print("Numune cinsini su numunesi veya çamur ve sediment numunesi şeklinde yazınız.")
 elif b==Klor:
  r=float(input("Numune için sarf edilen AgNO3 miktarı (mL)="))
  ş=float(input("Şahit numune için sarf edilen AgNO3 miktarı(mL)="))
  k=float(input("AgNO3'ın normalitesi="))
  d=float(input("Numune hacmi (mL)="))
  mg_Cl_L=(r-ş)*k*35450/d
  print("Klor=",mg_Cl_L,"mg Cl/L")
 elif b==Fosfor:
  ö=float(input("Ölçülen renkli çözeltinin absorbans değeri="))
  n=float(input("Çözeltideki fosfor konsantrasyonu(mg/L)="))
  i=float(input("fotometrik faktör="))
  fosfor_mg_L=(ö/n)*i
  print("Fosfor=",fosfor_mg_L,"mg fosfor/L")
elif a=="3":
 e=input("Oluşturmak istediğiniz grafik türünün numarasını giriniz.(sütun grafiği=1, pasta grafik=2, nokta grafik=3, çizgi grafik=4, alan grafik=5)")
 Sütun_grafiği= "1"
 Pasta_grafik= "2"
 Nokta_grafik= "3"
 Çizgi_grafik= "4"
 Alan_grafik= "5"
 if e=="1":
  from matplotlib import pyplot as plt
  x_values=[1,2,3,4]
  y_values=[1,2,3,4]
  x_eksen_baslıgı="konsantrasyon"
  y_eksen_baslıgı="zaman"
  baslık="fonksiyon"
  plt.bar(x_values,y_values,color='green')
  plt.xlabel(x_eksen_baslıgı)
  plt.ylabel(y_eksen_baslıgı)
  plt.title(baslık)
  plt.show()
 elif e=="2":
  kategoriler=['A','B','C','D']
  veriler=[30,15,45,10]
  baslık="koi"
  plt.pie(veriler,labels=kategoriler,autopct='%1.1f%%')
  plt.title(baslık)
  plt.show()
 elif e=="3":
  x=[1,2,3,4,5]
  y=[66,66,77,88,90]
  plt.scatter(x,y)
  plt.xlabel('X_ekseni')
  plt.ylabel('Y_ekseni')
  plt.title('Nokta grafiği')
  plt.show()
 elif e=="4":
  x=[1,2,3,4,5]
  y=[66,66,77,88,90]
  plt.plot(x,y)
  plt.xlabel('X_ekseni')
  plt.ylabel('Y_ekseni')
  plt.title('çizgi grafiği')
  plt.show()
 elif e=="5":
  x=[1,2,3,8,5]
  y=[66,33,77,88,90]
  plt.fill_between(x,y,color='lightblue')
  plt.xlabel('X_ekseni')
  plt.ylabel('Y_ekseni')
  plt.title('alan grafiği')
  plt.show()
 else:
  print("Hata, lütfen belirtilen numaralardan seçiminizi yapın.")
else:
 print("Hata, lütfen belirtilen numaralardan seçiminizi yapın.")



.

